apiVersion: cloudcredential.openshift.io/v1
kind: CredentialsRequest
metadata:
  name: azure-file-csi-driver-operator
  namespace: openshift-cloud-credential-operator
  annotations:
    include.release.openshift.io/self-managed-high-availability: "true"
    include.release.openshift.io/single-node-developer: "true"
    capability.openshift.io/name: Storage+CloudCredential
spec:
  serviceAccountNames:
  - azure-file-csi-driver-operator
  - azure-file-csi-driver-controller-sa
  - azure-file-csi-driver-node-sa
  providerSpec:
    apiVersion: cloudcredential.openshift.io/v1
    kind: AzureProviderSpec
    permissions:
      - 'Microsoft.Storage/storageAccounts/read'
      - 'Microsoft.Storage/storageAccounts/write'
      - 'Microsoft.Storage/storageAccounts/listKeys/action'
      - 'Microsoft.Storage/operations/read'
      - 'Microsoft.Network/virtualNetworks/subnets/write'
      - 'Microsoft.Network/virtualNetworks/subnets/read'
      - 'Microsoft.Network/virtualNetworks/subnets/*/read'
      - 'Microsoft.Network/privateEndpoints/write'
      - 'Microsoft.Network/privateEndpoints/read'
      - 'Microsoft.Network/privateEndpoints/privateDnsZoneGroups/write'
      - 'Microsoft.Network/privateDnsZones/write'
      - 'Microsoft.Network/privateDnsZones/virtualNetworkLinks/write'
      - 'Microsoft.Network/privateDnsZones/virtualNetworkLinks/read'
      - 'Microsoft.Network/privateDnsZones/read'
      - 'Microsoft.Network/privateDnsOperationStatuses/read'
      - 'Microsoft.Network/locations/operations/read'
  secretRef:
    name: azure-file-credentials
    namespace: openshift-cluster-csi-drivers

