resources:
  - ../../base
namespace: openshift-cluster-csi-drivers
patches:
  - path: claim_role.patch.yaml
    target:
      kind: Role
      version: v1
  - path: monitoring_role.patch.yaml
    target:
      kind: Role
      version: v1
  - patch: |-
      $patch: delete
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: aws-ebs-csi-driver-operator
        namespace: openshift-cluster-csi-drivers
